In [1]:
import torch

In [2]:
torch.manual_seed(0)

In [3]:
d = 20 # 特征维度
n = 100 # 训练样本数量
C = 10 # 类别的数量
t = 40 # 测试样本数量
K = 7 # 邻居数量

In [4]:
X_train = torch.rand(n, d)
y_train = torch.randint(1, C, (n,))
T = torch.rand(t, d)

In [5]:
T_squared = torch.sum(T ** 2, axis=1).reshape(-1, 1)
X_train_squared = torch.sum(X_train ** 2, axis=1).reshape(1, -1)
dist = T_squared + X_train_squared - 2 * T @ X_train.T  # (i,)+(,j)-(i, j)
print(dist)

tensor([[3.6316, 3.9224, 3.7948,  ..., 2.9056, 5.2984, 2.3613],
        [2.4834, 3.5503, 3.8866,  ..., 1.9331, 4.4838, 3.9127],
        [2.8477, 3.5900, 1.4597,  ..., 2.4509, 3.8432, 4.5834],
        ...,
        [2.4622, 4.1187, 3.0745,  ..., 2.5219, 2.6697, 3.6736],
        [2.5319, 1.8156, 3.6772,  ..., 3.8384, 2.2318, 3.3201],
        [3.4255, 4.3354, 3.5619,  ..., 2.1941, 4.8147, 3.8205]])


In [6]:
torch.argsort(dist, dim=1)

tensor([[44, 39, 10,  ...,  7, 98, 60],
        [88, 54, 97,  ..., 23, 53, 84],
        [31, 87, 11,  ..., 16, 46, 29],
        ...,
        [ 6, 82, 47,  ...,  4, 37, 48],
        [ 1, 12,  6,  ..., 62, 28, 22],
        [54, 88, 79,  ..., 12, 98, 91]])

In [7]:
y_train

tensor([6, 8, 1, 7, 4, 6, 1, 7, 8, 5, 1, 4, 6, 5, 5, 8, 7, 5, 9, 9, 3, 6, 7, 2,
        4, 7, 5, 4, 6, 3, 8, 4, 8, 9, 5, 9, 3, 8, 1, 8, 3, 4, 6, 8, 1, 6, 7, 7,
        4, 2, 3, 6, 4, 2, 2, 3, 1, 5, 9, 3, 6, 2, 3, 6, 6, 1, 6, 7, 2, 2, 9, 5,
        3, 5, 1, 7, 9, 1, 9, 1, 2, 4, 4, 6, 5, 3, 6, 9, 6, 2, 3, 8, 5, 1, 1, 9,
        9, 2, 6, 4])

In [8]:
y_train[torch.argsort(dist, dim=1)[:, :K]]

tensor([[1, 8, 1, 1, 9, 8, 4],
        [6, 2, 2, 3, 5, 6, 6],
        [4, 9, 4, 1, 3, 8, 2],
        [3, 9, 6, 7, 4, 9, 3],
        [2, 3, 9, 4, 1, 3, 3],
        [3, 9, 7, 6, 1, 4, 6],
        [4, 3, 7, 5, 6, 3, 8],
        [3, 3, 2, 6, 9, 2, 6],
        [4, 2, 2, 6, 7, 6, 6],
        [2, 2, 8, 9, 6, 1, 1],
        [1, 6, 1, 9, 1, 9, 3],
        [6, 2, 1, 8, 5, 7, 7],
        [5, 4, 2, 4, 6, 3, 5],
        [6, 4, 4, 8, 3, 9, 9],
        [8, 2, 2, 2, 6, 6, 5],
        [6, 6, 1, 8, 2, 9, 2],
        [9, 2, 7, 3, 3, 7, 1],
        [1, 1, 3, 6, 9, 2, 4],
        [2, 8, 7, 9, 5, 4, 2],
        [2, 4, 8, 6, 9, 5, 4],
        [3, 6, 5, 1, 6, 2, 3],
        [5, 6, 4, 8, 8, 2, 1],
        [2, 8, 1, 6, 1, 1, 9],
        [8, 1, 3, 1, 3, 9, 2],
        [2, 6, 4, 6, 2, 9, 7],
        [2, 1, 3, 6, 1, 6, 4],
        [7, 2, 8, 8, 9, 3, 4],
        [4, 2, 6, 3, 1, 9, 8],
        [2, 4, 6, 8, 4, 4, 5],
        [6, 6, 1, 5, 7, 1, 4],
        [7, 3, 1, 6, 5, 4, 2],
        [8, 4, 2, 9, 9, 3, 6],
        

In [9]:
k_nearest_labels = y_train[torch.argsort(dist, dim=1)[:, :K]]
print(k_nearest_labels)

tensor([[1, 8, 1, 1, 9, 8, 4],
        [6, 2, 2, 3, 5, 6, 6],
        [4, 9, 4, 1, 3, 8, 2],
        [3, 9, 6, 7, 4, 9, 3],
        [2, 3, 9, 4, 1, 3, 3],
        [3, 9, 7, 6, 1, 4, 6],
        [4, 3, 7, 5, 6, 3, 8],
        [3, 3, 2, 6, 9, 2, 6],
        [4, 2, 2, 6, 7, 6, 6],
        [2, 2, 8, 9, 6, 1, 1],
        [1, 6, 1, 9, 1, 9, 3],
        [6, 2, 1, 8, 5, 7, 7],
        [5, 4, 2, 4, 6, 3, 5],
        [6, 4, 4, 8, 3, 9, 9],
        [8, 2, 2, 2, 6, 6, 5],
        [6, 6, 1, 8, 2, 9, 2],
        [9, 2, 7, 3, 3, 7, 1],
        [1, 1, 3, 6, 9, 2, 4],
        [2, 8, 7, 9, 5, 4, 2],
        [2, 4, 8, 6, 9, 5, 4],
        [3, 6, 5, 1, 6, 2, 3],
        [5, 6, 4, 8, 8, 2, 1],
        [2, 8, 1, 6, 1, 1, 9],
        [8, 1, 3, 1, 3, 9, 2],
        [2, 6, 4, 6, 2, 9, 7],
        [2, 1, 3, 6, 1, 6, 4],
        [7, 2, 8, 8, 9, 3, 4],
        [4, 2, 6, 3, 1, 9, 8],
        [2, 4, 6, 8, 4, 4, 5],
        [6, 6, 1, 5, 7, 1, 4],
        [7, 3, 1, 6, 5, 4, 2],
        [8, 4, 2, 9, 9, 3, 6],
        

In [11]:
y_pred = torch.zeros(T.shape[0])
for row in range(k_nearest_labels.shape[0]):
    y_pred[row] = torch.bincount(k_nearest_labels[row]).argmax()

In [12]:
torch.bincount(k_nearest_labels[row])

tensor([0, 2, 2, 0, 0, 0, 2, 0, 0, 1])

In [13]:
torch.bincount(k_nearest_labels[row]).argmax()

tensor(1)